-- Initial schema migration
-- DOWN

DROP TABLE IF EXISTS trade_executions CASCADE;
DROP TABLE IF EXISTS consistency_logs CASCADE;
DROP TABLE IF EXISTS adversarial_news CASCADE;
DROP TABLE IF EXISTS regime_logs CASCADE;
DROP TABLE IF EXISTS backtest_runs CASCADE;
DROP TABLE IF EXISTS strategies CASCADE;
DROP TABLE IF EXISTS candles CASCADE;
DROP TABLE IF EXISTS market_ticks CASCADE;
DROP TABLE IF EXISTS credentials CASCADE;
DROP TABLE IF EXISTS provider_symbols CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS symbols CASCADE;
