-- 000015: Feature vector store hypertable
-- Persists 21-dim feature vectors computed per symbol per candle for
-- offline ML model training. Populated by the Go feature store at runtime
-- and read by the Python training dataset builder.
-- TimescaleDB hypertable with compression (7-day) and retention (90-day).

CREATE TABLE IF NOT EXISTS feature_vectors (
    time        TIMESTAMPTZ NOT NULL,
    symbol      TEXT NOT NULL,
    features    DOUBLE PRECISION[] NOT NULL,
    target      SMALLINT,
    signal_type TEXT,
    regime      SMALLINT
);

-- Convert to hypertable partitioned by time
SELECT create_hypertable('feature_vectors', 'time', if_not_exists => true);

-- Enable compression: segment by symbol for efficient per-symbol queries
ALTER TABLE feature_vectors SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol',
    timescaledb.compress_orderby = 'time DESC'
);

-- Compress chunks older than 7 days
SELECT add_compression_policy('feature_vectors', INTERVAL '7 days', if_not_exists => true);

-- Retain 90 days of feature vectors for training
SELECT add_retention_policy('feature_vectors', INTERVAL '90 days', if_not_exists => true);

-- Index for training dataset queries
CREATE INDEX IF NOT EXISTS idx_feature_vectors_symbol_time
    ON feature_vectors (symbol, time DESC);

-- Index for regime-stratified queries
CREATE INDEX IF NOT EXISTS idx_feature_vectors_regime_time
    ON feature_vectors (regime, time DESC);

-- Comments for documentation
COMMENT ON TABLE feature_vectors IS '21-dim ML feature vectors per symbol per candle for offline training';
COMMENT ON COLUMN feature_vectors.features IS '21-element double precision array matching orca.ml.config.FEATURE_NAMES order';
COMMENT ON COLUMN feature_vectors.target IS 'Binary target label (1=win, 0=loss) generated by triple-barrier method';
