package backtest

import (
	"fmt"
	"strings"
	"time"
)

type GKRExportConfig struct {
	StrategyName    string
	StrategyType    string
	BestParams      map[string]float64
	OOSSharpe       float64
	PassProbability float64
	TotalReturnPct  float64
	MaxDrawdownPct  float64
	NumTrades       int
	GeneratedAt     time.Time
	SourceVersion   string
}

func DefaultGKRExportConfig() GKRExportConfig {
	return GKRExportConfig{
		SourceVersion: "orca-backtest/1.0",
		GeneratedAt:   time.Now(),
	}
}

func ExportGKRConfig(cfg GKRExportConfig) string {
	var sb strings.Builder

	sb.WriteString("# Generated by OrcaAlgo Continuous Validation Pipeline\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n", cfg.GeneratedAt.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("# Source: %s\n", cfg.SourceVersion))
	sb.WriteString(fmt.Sprintf("# Strategy: %s (%s)\n", cfg.StrategyName, cfg.StrategyType))
	sb.WriteString(fmt.Sprintf("# OOS Sharpe: %.2f | Pass Prob: %.1f%% | Return: %.1f%% | MaxDD: %.1f%% | Trades: %d\n",
		cfg.OOSSharpe, cfg.PassProbability, cfg.TotalReturnPct, cfg.MaxDrawdownPct, cfg.NumTrades))
	sb.WriteString("#\n")
	sb.WriteString(fmt.Sprintf("strategy_id: \"%s\"\n", cfg.StrategyName))
	sb.WriteString(fmt.Sprintf("strategy_type: \"%s\"\n", cfg.StrategyType))
	sb.WriteString(fmt.Sprintf("ir_version: \"qst-ir/0.4\"\n"))
	sb.WriteString("\n")
	sb.WriteString("capabilities:\n")
	sb.WriteString(fmt.Sprintf("  - name: core\n"))
	sb.WriteString(fmt.Sprintf("    version: \"1.0\"\n"))
	sb.WriteString("\n")
	sb.WriteString("parameters:\n")
	sb.WriteString(fmt.Sprintf("  lookback: %d\n", intParam(cfg.BestParams, "lookback", 20)))
	sb.WriteString(fmt.Sprintf("  entry_z: %.1f\n", cfg.BestParams["entry_z"]))
	sb.WriteString(fmt.Sprintf("  exit_z: %.1f\n", cfg.BestParams["exit_z"]))
	sb.WriteString(fmt.Sprintf("  fast_period: %d\n", intParam(cfg.BestParams, "fast_period", 20)))
	sb.WriteString(fmt.Sprintf("  slow_period: %d\n", intParam(cfg.BestParams, "slow_period", 50)))
	sb.WriteString(fmt.Sprintf("  atr_period: %d\n", intParam(cfg.BestParams, "atr_period", 14)))
	sb.WriteString(fmt.Sprintf("  atr_multiplier: %.1f\n", floatParam(cfg.BestParams, "atr_multiplier", 2.0)))
	sb.WriteString(fmt.Sprintf("  range_minutes: %d\n", intParam(cfg.BestParams, "range_minutes", 5)))
	sb.WriteString(fmt.Sprintf("  entry_buffer_pct: %.2f\n", floatParam(cfg.BestParams, "entry_buffer_pct", 0.1)))
	sb.WriteString(fmt.Sprintf("  grid_levels: %d\n", intParam(cfg.BestParams, "grid_levels", 4)))
	sb.WriteString(fmt.Sprintf("  grid_spacing: %.1f\n", floatParam(cfg.BestParams, "grid_spacing", 1.0)))
	sb.WriteString("\n")
	sb.WriteString("validation:\n")
	sb.WriteString(fmt.Sprintf("  oos_sharpe: %.2f\n", cfg.OOSSharpe))
	sb.WriteString(fmt.Sprintf("  pass_probability: %.1f\n", cfg.PassProbability))
	sb.WriteString(fmt.Sprintf("  total_return_pct: %.1f\n", cfg.TotalReturnPct))
	sb.WriteString(fmt.Sprintf("  max_drawdown_pct: %.1f\n", cfg.MaxDrawdownPct))
	sb.WriteString(fmt.Sprintf("  num_trades: %d\n", cfg.NumTrades))
	sb.WriteString(fmt.Sprintf("  validated_at: \"%s\"\n", cfg.GeneratedAt.Format(time.RFC3339)))

	return sb.String()
}

func ExportGKRFromWalkForward(owr *OptimizedWalkForwardResult, mcResult *MonteCarloResult, strategyID string) string {
	cfg := DefaultGKRExportConfig()
	cfg.StrategyName = strategyID
	cfg.StrategyType = strategyID
	cfg.OOSSharpe = owr.AvgOOSSharpe
	cfg.TotalReturnPct = owr.TotalReturnPct
	cfg.MaxDrawdownPct = 0
	cfg.NumTrades = 0

	for _, w := range owr.Windows {
		if w.OOSReturnPct < 0 && -w.OOSReturnPct > cfg.MaxDrawdownPct {
			cfg.MaxDrawdownPct = -w.OOSReturnPct
		}
		cfg.NumTrades += w.OOSTrades
	}

	if mcResult != nil {
		cfg.PassProbability = mcResult.PassProbability
	}

	if owr.IVSActive && len(owr.IVSRobustParamsPerWindow) > 0 {
		cfg.BestParams = owr.IVSRobustParamsPerWindow[len(owr.IVSRobustParamsPerWindow)-1]
	} else if len(owr.BestParamsPerWindow) > 0 {
		cfg.BestParams = owr.BestParamsPerWindow[len(owr.BestParamsPerWindow)-1]
	} else {
		cfg.BestParams = make(map[string]float64)
	}

	return ExportGKRConfig(cfg)
}

func intParam(params map[string]float64, key string, defaultVal int) int {
	if v, ok := params[key]; ok {
		return int(v)
	}
	return defaultVal
}

func floatParam(params map[string]float64, key string, defaultVal float64) float64 {
	if v, ok := params[key]; ok {
		return v
	}
	return defaultVal
}
